import {assetVersionPattern} from './asset_version.mjs';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const html = readFileSync(new URL('../mobile/index.html', import.meta.url), 'utf8');
const css = readFileSync(new URL('../mobile/app.css', import.meta.url), 'utf8');
const app = readFileSync(new URL('../mobile/app.js', import.meta.url), 'utf8');

for (const id of ['screen-home', 'screen-setting', 'screen-juggler', 'screen-check', 'screen-scan', 'screen-guide', 'screen-planner', 'screen-trend', 'screen-target-map', 'screen-floor-map', 'screen-strategy', 'screen-results', 'screen-settings']) {
  assert.match(html, new RegExp(`id="${id}"`), `${id} が必要`);
}

assert.match(html, /id="screen-home" class="screen active"/, 'ホーム画面を最初に表示する');
assert.equal((html.match(/class="nav-button/g) || []).length, 13, 'モード別に切り替える専用メニューを持つ');
assert.match(html, /data-screen-target="check"/, 'ホームからハイエナ判定へ移動できる');
assert.match(html, /data-screen-target="planner"/, 'ホームから狙い台捜索へ移動できる');
assert.match(html, /data-screen-target="juggler"/, 'ホームからジャグラー判定へ移動できる');
assert.match(html, /data-screen-target="setting"/, 'ホームからスマスロ設定判別へ移動できる');
assert.match(html, /id="setting-assess-form"/, 'スマスロの営業中設定判別フォームが必要');
assert.match(html, /id="setting-elements"/, '機種固有の設定差項目を入力できる');
assert.match(app, /element_trials/, '割合項目は試行回数を分けて送信する');
assert.doesNotMatch(html, /data-screen="candidates"/, '候補台は狙い目画面へ統合する');
assert.match(html, /data-screen="planner"/, '明日の狙い台を独立メニューにする');
assert.match(html, /id="planner-form"/, '狙い台を登録できる');
assert.match(html, /id="planner-list"/, '狙い台を独立して一覧表示する');
assert.match(html, /id="target-search-form"/, '蓄積データから狙い台を検索できる');
assert.match(html, /id="event-ai-form"/, 'イベント分析へ根拠限定の質問欄を表示する');
assert.match(html, /id="event-model-audit"/, 'スマホ版に自動答え合わせの監査表示を追加する');
assert.match(html, /id="mobile-region-coverage"/, 'スマホ版に四條畷周辺の店舗別充足度を表示する');
assert.match(app, /region_data_coverage/, 'スマホ版で地域データ充足度APIを使用する');
assert.match(app, /region_board/, 'スマホ版で候補外を含む地域8店舗ボードを表示する');
assert.match(app, /公開元が差枚未掲載|collection_label/, 'スマホ版で公開未掲載と取得状態を区別する');
assert.match(app, /renderEventModelAudit/, 'スマホ版でモデル検証件数を描画する');
assert.match(app, /api\/ai\/event_ask/, 'イベント専用の根拠限定AI APIを利用する');
assert.match(app, /AIによる判定変更なし/, 'AIが候補判定を変更しないことを明示する');
assert.match(html, /id="target-search-results"/, '分析ランキングを表示できる');
assert.match(html, /id="target-search-region"/, '狙い台検索の対象地域を選べる');
assert.match(html, /id="target-search-accuracy"/, '70%・80%の精度優先モードを選べる');
assert.match(html, /id="target-search-progress"/, '狙い台分析中の進行度を表示する');
assert.match(app, /startTargetSearchProgress/, '分析段階と残り時間の目安を更新する');
assert.match(app, /target_accuracy=/, '選んだ精度基準を分析APIへ送る');
assert.match(app, /seat_role/, '台番号を第一候補・第二候補・避ける台に分けて表示する');
assert.match(app, /参考1位/, '安全基準未達の台番号は参考順位として表示する');
assert.match(app, /standalone_action/, '店舗判定と機種単体判定を分けて表示する');
assert.match(html, /月プラスを狙う使い方/, '実戦向けの月間運用手順を表示する');
assert.match(html, /id="target-map-form"/, '指定日で店舗ヒートマップを更新できる');
assert.match(html, /id="target-heat-map"/, '地図上に店舗の熱量を表示できる');
assert.match(html, /id="target-map-long-days"/, '長期表示期間を選べる');
assert.match(html, /id="target-map-region"/, '店舗マップの対象地域を選べる');
assert.match(html, /id="trend-form"/, '店舗ごとの傾向分析を持つ');
assert.match(html, /id="ai-comparison-panel"/, 'スマホ版に複数AIの共通条件比較を表示する');
assert.match(app, /mountAiComparison/, 'スマホ版で外部通信なしの準備確認と実測を分ける');
assert.match(html, /店舗別の強い機種を見る/, '狙い台捜索から店舗×機種分析へ移動できる');
assert.match(app, /api\/hall\/machine_strength_matrix/, '店舗ごとの強い機種を横断分析する');
assert.match(app, /recommendation_lower_bound_pct/, '機種別70%判定の95%下限を表示する');
assert.match(app, /hall_assessment/, '店舗の優良・回収傾向を表示する');
assert.match(app, /公開実績評価/, '店舗評価が断定ではなく公開実績ベースだと明示する');
assert.match(html, /id="floor-form"/, '店内座席ヒートマップを持つ');
assert.match(html, /id="floor-editor-form"/, '出典付きレイアウト編集を持つ');
assert.match(html, /id="screen-strategy"/, '分析から保存した朝一作戦を独立表示する');
assert.match(html, /data-module-nav="hyena"/, 'ハイエナ専用メニューが必要');
assert.match(html, /data-module-nav="target"/, '狙い台専用メニューが必要');
assert.match(html, /data-module-nav="juggler"/, 'ジャグラー専用メニューが必要');
assert.match(html, /data-screen-target="guide"/, '判定画面から狙い目へ移動できる');
assert.match(html, /id="scan-hall-form"/, '店舗を選ぶ巡回モードが必要');
assert.match(html, /id="hyena-store-ranking"/, '今から向かう候補店の自動ランキングが必要');
assert.match(html, /id="hyena-store-at"[^>]*datetime-local/, '巡回日時を指定して再計算できる');
assert.match(html, /id="hyena-store-prefecture"/, '四條畷周辺の店舗ランキング地域を表示する');
assert.match(html, /id="occupancy-avg-rotation"/, '店舗の平均回転数を現場で記録できる');
assert.match(app, /api\/occupancy\/hyena-stores/, '自動店舗ランキングAPIを利用する');
assert.match(app, /pachi-hyena-prefecture/, '選択した地域を端末に保持する');
assert.match(html, /id="scan-machine-list"/, '設置機種だけの巡回リストが必要');
assert.match(html, /id="performance-chart"/, '期待値と実収支の比較グラフを表示する');
assert.match(html, /id="performance-summary"/, '比較指標を表示する');
assert.match(html, /id="catalog-scope"/, '現在の対象機種を明示する');
assert.match(html, /スロット攻略ホーム/, '複数の攻略モードを持つことを明示する');
assert.match(html, /id="juggler-assess-form"/, 'ジャグラーの営業中判定フォームが必要');
assert.match(html, /id="juggler-target-form"/, 'ジャグラーの朝一候補フォームが必要');
assert.match(html, /value="shijonawate" selected>四條畷駅周辺/, '四條畷駅周辺を重点地域にする');
assert.match(app, /api\/juggler\/assess/, '公式確率を使うジャグラー判定APIを利用する');
assert.match(app, /api\/juggler\/targets/, 'ジャグラー朝一候補APIを利用する');
assert.match(html, /id="mobile-version-button"/, 'ヘッダーから更新内容を開ける');
assert.match(html, /id="patch-notes-group"/, '設定画面にパッチノートを表示する');
assert.match(html, /id="mobile-ai-status"/, '設定画面でAI接続先と送信範囲を確認できる');
assert.match(app, /api\/ai\/status/, 'APIキーを端末に保存せずサーバーのAI接続状態を確認する');
assert.match(html, assetVersionPattern('app.css'));
assert.match(html, assetVersionPattern('app.js'));
assert.match(html, /id="scan-strategy-time"/, '時間帯別の立ち回りを確認できる');
assert.match(html, /id="scan-data-coverage"/, '巡回店舗のデータ量を明示する');
assert.match(html, /id="trend-data-coverage"/, '傾向分析の根拠データ量を明示する');
assert.match(app, /TIME_STRATEGIES/, '朝一から閉店前までの戦略を切り替える');
assert.match(app, /data_coverage/, '店舗ごとのデータ充足度APIを使用する');
assert.match(html, /着席前30秒チェック/, 'ゲーム数だけで判断しない現場チェックが必要');
assert.match(html, /今日の使い方/, '店内での実戦手順をスマホから確認できる');
assert.match(app, /data-seat-confirm/, '着席候補を保存する前に現物確認を要求する');
assert.match(app, /データ信頼度/, '判定結果からデータの信頼度を確認できる');
assert.match(html, /上のゲーム数だけでは決めない/, 'データカウンターだけの判断を防ぐ');
assert.match(app, /この判定で見る数字/, '判定結果に入力指標を再表示する');
assert.match(app, /catalog\.json\?v=\$\{APP_VERSION\}/, '機種追加時に古いカタログキャッシュを使わない');
assert.match(app, assetVersionPattern('core.mjs'), '内部判定ロジックも更新時にキャッシュを破棄する');
assert.match(html, /id="floor-collection-progress"/, '現地・CSV補完の30日進捗を表示する');
assert.match(app, /api\/layouts\/seat_results\/status/, '台番号実績の補完進捗APIを利用する');
assert.match(app, /data-collect-hall/, '不足店舗から補完画面へ直接移動できる');
assert.match(html, /id="floor-diff-quick"/, '現地で差枚をワンタップ入力できる');
assert.match(html, /保存して次の台へ/, '連続入力の流れを明示する');
assert.match(app, /loadFloorDailyResults/, '当日の登録件数と直近入力を表示する');
assert.match(app, /quality_gate/, '現地データの品質ゲートを表示する');
assert.match(app, /renderTargetConclusion/, '狙い台検索の最上部に行く日の結論を表示する');
assert.match(app, /selectTargetMachine\(item, true\)/, '同じ安全ランクなら台番号履歴のある店舗と機種を優先する');
assert.match(app, /status === '検証済み'/, '70%実戦基準未達の台番号を確定表示しない');
assert.match(css, /\.target-conclusion\s*\{[^}]*position:\s*sticky/s, '行く日の結論はスクロール中も確認できる');
assert.match(app, /recommendation_success_pct/, '狙い台の過去検証成績を表示する');
assert.match(app, /model_consensus_pct/, '複数予測モデルの一致度を表示する');
assert.match(app, /calibrated_positive_rate_pct/, '過去検証で補正したプラス確率を表示する');
assert.match(app, /forecast_interval_coins/, '点予測だけでなく予測幅を表示する');
assert.match(app, /regime_stability_pct/, '直近の相場変化を表示する');
assert.match(app, /prediction_audit/, '先読み検証・確率補正・相場変化の監査件数を表示する');
assert.match(app, /保存できません：/, '検証基準に満たない候補は作戦保存を止める');
assert.match(app, /installation_snapshot/, '店舗の設置機種を使って巡回対象を絞る');
assert.match(app, /start_threshold\) - 100/, 'ボーダー100G手前を通過ラインとして表示する');
assert.match(html, /id="patrol-observation-form"/, '台番号別の巡回記録を入力できる');
assert.match(html, /id="validation-summary"/, '期待値ボーダーを実戦結果で検証できる');
assert.match(html, /id="sync-push-button"/, '端末間のサーバー同期を操作できる');
assert.match(html, /id="quick-section-diff"/, '有利区間差枚を入力できる');
assert.match(html, /id="quick-replay-used"/, '再プレイ使用枚数を保持できる');
assert.match(html, /id="quick-templates"/, '頻出入力をワンタップで反映できる');
assert.match(html, /id="quick-ocr-file"/, 'カメラOCR入力を利用できる');
assert.match(html, /id="reset-record-form"/, '店舗別リセット・据え置き癖を記録できる');
assert.match(html, /id="archive-collector-group"/, '設定から過去データ収集を管理できる');
assert.match(html, /id="collection-health-group"/, '設定から毎日の収集状態を確認できる');
assert.match(html, /id="mobile-archive-pause"/, 'iPhoneから収集を一時停止できる');
assert.match(html, /id="mobile-archive-resume"/, 'iPhoneから収集を再開できる');
assert.match(app, /api\/scrape\/archive\/status/, '過去データ収集の進捗APIを利用する');
assert.match(app, /api\/scrape\/health/, '収集元ごとの成功・失敗状態を取得する');
assert.match(app, /api\/events\/quality/, 'イベントの予測対象・隔離件数を確認する');
assert.match(html, /id="mobile-event-quality"/, 'スマホ版でイベントデータ品質を表示する');
assert.match(html, /id="event-analysis-results"/, '狙い台画面に今後のイベントと過去成績を表示する');
assert.match(app, /api\/events\/analysis/, 'イベント名×店舗×機種の実績分析APIを利用する');
assert.match(app, /実績3回未満は「未検証」/, '少数実績を熱いイベントと断定しない');
assert.match(app, /先読み答え合わせ/, 'イベント開催日より前の情報だけで答え合わせした成績を表示する');
assert.match(app, /applyPersonalCalibration/, '実戦結果で期待値を安全側へ補正する');
assert.match(app, /pending_count/, 'オフライン変更を未送信キューとして保持する');
assert.match(app, /outcome_labels/, 'スマホ実戦記録でも本人収支と期待値を別ラベルで保存する');
assert.match(app, /正解：本人収支/, 'スマホ画面で収支と設定正解を混同しない');
assert.match(html, /id="result-hit-game"/, '当選ゲーム数を詳細記録できる');
assert.match(html, /id="brand-home"[^>]*data-screen-target="home"/, '左上ブランドからホームへ戻れる');
assert.match(html, /id="mobile-menu-button"/, '全画面共通のメニューボタンが必要');
assert.match(html, /id="mobile-menu-overlay"/, '開閉できる全機能メニューが必要');
for (const target of ['home', 'setting', 'juggler', 'check', 'scan', 'guide', 'planner', 'trend', 'target-map', 'floor-map', 'strategy', 'results', 'settings']) {
  assert.match(html, new RegExp(`data-menu-screen[^>]*data-screen-target="${target}"`), `共通メニューに ${target} が必要`);
}
assert.match(app, /hostname === 'yoshirou911\.github\.io'/, '公開PWAではAPI接続先を切り替える');
assert.match(app, /https:\/\/pachi-tool\.fly\.dev/, '公開PWAの分析API接続先が必要');
assert.match(css, /min-height:\s*calc\(68px \+ var\(--safe-bottom\)\)/, '下部メニューのタップ領域を確保する');

assert.match(html, /id="quick-exchange-rate"[^>]*min="5"[^>]*step="0\.1"/);

console.log('mobile UI contract tests passed');
